# Generated by Django 4.2.2 on 2023-06-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plaintext_password',
        ),
    ]
